INSERT INTO food_items (id, name, category, price, is_available) VALUES (1, 'Apple Pie', 'desserts', 9.99, TRUE);
INSERT INTO food_items (id, name, category, price, is_available) VALUES (2, 'Brownie with Walnuts', 'desserts', 9.99, TRUE);
INSERT INTO food_items (id, name, category, price, is_available) VALUES (3, 'Caprese Salad', 'appetizers', 9.99, TRUE);
INSERT INTO food_items (id, name, category, price, is_available) VALUES (4, 'Cheeseburger', 'main course', 9.99, TRUE);
INSERT INTO food_items (id, name, category, price, is_available) VALUES (5, 'Chocolate Cake', 'desserts', 9.99, TRUE);
INSERT INTO food_items (id, name, category, price, is_available) VALUES (6, 'Fish and Chips', 'main course', 9.99, TRUE);
INSERT INTO food_items (id, name, category, price, is_available) VALUES (7, 'Fruit Bowl', 'snacks', 9.99, TRUE);
INSERT INTO food_items (id, name, category, price, is_available) VALUES (8, 'Garlic Bread', 'appetizers', 9.99, TRUE);
INSERT INTO food_items (id, name, category, price, is_available) VALUES (9, 'Grilled Chicken Sandwich', 'main course', 9.99, TRUE);
INSERT INTO food_items (id, name, category, price, is_available) VALUES (10, 'Macarons', 'desserts', 9.99, TRUE);
INSERT INTO food_items (id, name, category, price, is_available) VALUES (11, 'Margherita Pizza', 'main course', 9.99, TRUE);
INSERT INTO food_items (id, name, category, price, is_available) VALUES (12, 'Mixed Nuts', 'snacks', 9.99, TRUE);
INSERT INTO food_items (id, name, category, price, is_available) VALUES (13, 'Mozzarella Sticks', 'appetizers', 9.99, TRUE);
INSERT INTO food_items (id, name, category, price, is_available) VALUES (14, 'Nachos', 'snacks', 9.99, TRUE);
INSERT INTO food_items (id, name, category, price, is_available) VALUES (15, 'Popcorn', 'snacks', 9.99, TRUE);
INSERT INTO food_items (id, name, category, price, is_available) VALUES (16, 'Potato Chips', 'snacks', 9.99, TRUE);
INSERT INTO food_items (id, name, category, price, is_available) VALUES (17, 'Pretzels', 'snacks', 9.99, TRUE);
INSERT INTO food_items (id, name, category, price, is_available) VALUES (18, 'Protein Bar', 'snacks', 9.99, TRUE);
INSERT INTO food_items (id, name, category, price, is_available) VALUES (19, 'BBQ Ribs', 'main course', 9.99, TRUE);
INSERT INTO food_items (id, name, category, price, is_available) VALUES (20, 'Spaghetti Bolognese', 'main course', 9.99, TRUE);
INSERT INTO food_items (id, name, category, price, is_available) VALUES (21, 'Spring Rolls', 'appetizers', 9.99, TRUE);
INSERT INTO food_items (id, name, category, price, is_available) VALUES (22, 'Sprinkle Donut', 'desserts', 9.99, TRUE);
INSERT INTO food_items (id, name, category, price, is_available) VALUES (23, 'Strawberry Cheesecake', 'desserts', 9.99, TRUE);
INSERT INTO food_items (id, name, category, price, is_available) VALUES (24, 'Stuffed Mushrooms', 'appetizers', 9.99, TRUE);
INSERT INTO food_items (id, name, category, price, is_available) VALUES (25, 'Vanilla Ice Cream', 'desserts', 9.99, TRUE);
INSERT INTO food_items (id, name, category, price, is_available) VALUES (26, 'Veggie Burrito', 'main course', 9.99, TRUE);
INSERT INTO food_items (id, name, category, price, is_available) VALUES (27, 'Veggies with Hummus', 'appetizers', 9.99, TRUE);
INSERT INTO food_items (id, name, category, price, is_available) VALUES (28, 'Wings', 'appetizers', 9.99, TRUE);
