INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Mozzarella Sticks', 13.54, '/images/mozzarella_sticks.png', 'appetizers', TRUE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Chicken Wings', 2.62, '/images/chicken_wings.png', 'snacks', TRUE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Spring Rolls', 9.91, '/images/spring_rolls.png', 'desserts', FALSE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Garlic Bread', 9.04, '/images/garlic_bread.png', 'appetizers', TRUE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Caprese Salad', 2.08, '/images/caprese_salad.png', 'snacks', FALSE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Nachos', 15.67, '/images/nachos.png', 'appetizers', TRUE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Stuffed Mushrooms', 7.54, '/images/stuffed_mushrooms.png', 'appetizers', FALSE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Cheeseburger', 24.5, '/images/cheeseburger.png', 'main course', TRUE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Grilled Chicken Sandwich', 14.7, '/images/grilled_chicken_sandwich.png', 'desserts', TRUE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Margherita Pizza', 14.22, '/images/margherita_pizza.png', 'snacks', TRUE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Spaghetti Bolognese', 5.35, '/images/spaghetti_bolognese.png', 'main course', TRUE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Fish and Chips', 15.62, '/images/fish_and_chips.png', 'appetizers', TRUE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Veggie Burrito', 12.07, '/images/veggie_burrito.png', 'snacks', TRUE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('BBQ Ribs', 6.49, '/images/bbq_ribs.png', 'appetizers', TRUE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Chocolate Cake', 13.4, '/images/chocolate_cake.png', 'snacks', FALSE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Vanilla Ice Cream', 21.15, '/images/vanilla_ice_cream.png', 'main course', FALSE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Strawberry Cheesecake', 7.3, '/images/strawberry_cheesecake.png', 'main course', FALSE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Apple Pie', 19.52, '/images/apple_pie.png', 'main course', TRUE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Brownie with Walnuts', 19.52, '/images/brownie_with_walnuts.png', 'appetizers', TRUE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Macarons', 3.71, '/images/macarons.png', 'snacks', TRUE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Donut with Sprinkles', 16.73, '/images/donut_with_sprinkles.png', 'main course', TRUE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Popcorn', 4.19, '/images/popcorn.png', 'main course', FALSE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Potato Chips', 7.8, '/images/potato_chips.png', 'appetizers', TRUE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Pretzels', 5.69, '/images/pretzels.png', 'appetizers', FALSE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Fruit Cup', 18.63, '/images/fruit_cup.png', 'appetizers', TRUE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Protein Bar', 20.14, '/images/protein_bar.png', 'desserts', TRUE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Hummus with Veggie Sticks', 5.18, '/images/hummus_with_veggie_sticks.png', 'appetizers', FALSE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Trail Mix', 7.22, '/images/trail_mix.png', 'desserts', TRUE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Food Item 29', 22.41, '/images/food_item_29.png', 'main course', FALSE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Food Item 30', 6.13, '/images/food_item_30.png', 'snacks', TRUE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Food Item 31', 8.49, '/images/food_item_31.png', 'desserts', TRUE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Food Item 32', 15.29, '/images/food_item_32.png', 'desserts', FALSE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Food Item 33', 17.68, '/images/food_item_33.png', 'snacks', FALSE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Food Item 34', 10.17, '/images/food_item_34.png', 'snacks', TRUE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Food Item 35', 5.09, '/images/food_item_35.png', 'desserts', TRUE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Food Item 36', 14.21, '/images/food_item_36.png', 'desserts', FALSE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Food Item 37', 11.15, '/images/food_item_37.png', 'snacks', TRUE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Food Item 38', 4.91, '/images/food_item_38.png', 'desserts', FALSE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Food Item 39', 18.76, '/images/food_item_39.png', 'snacks', TRUE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Food Item 40', 14.09, '/images/food_item_40.png', 'snacks', TRUE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Food Item 41', 10.88, '/images/food_item_41.png', 'snacks', TRUE);
INSERT INTO Food_Items (name, price, image_path, category, is_available) VALUES ('Food Item 42', 16.24, '/images/food_item_42.png', 'snacks', FALSE);